"""add chunk retrieval

Revision ID: f583a18bd33a
Revises: ae9e8a069b06
Create Date: 2026-06-17 01:46:13.090428

"""
from typing import Sequence, Union
import pgvector

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f583a18bd33a'
down_revision: Union[str, Sequence[str], None] = 'ae9e8a069b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_note_id'), 'document_chunks', ['note_id'], unique=False)
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id')
    )
    op.execute(
    "DROP TABLE IF EXISTS vector_test2"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_test2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vector_test2_pkey'))
    )
    op.drop_table('chunk_embeddings')
    op.drop_index(op.f('ix_document_chunks_note_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
